In [1]:
import numpy as np

In [2]:
arr_2d = np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]))
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [3]:
arr_2d[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [4]:
arr_2d[3][4]

20

In [5]:
arr.max()

NameError: name 'arr' is not defined

In [6]:
np.arange(26)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [7]:
arr.reshape(5,5)

NameError: name 'arr' is not defined

In [8]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
arr.reshape(5,5)

NameError: name 'arr' is not defined

In [10]:
arr.max()

NameError: name 'arr' is not defined

In [1]:
arr_2d = np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]))
arr_2d

NameError: name 'np' is not defined