In [8]:
import numpy as np

In [12]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [10]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [4]:
arr_2d = np.array(([0,1,2],[3,4,5],[6,7,8]))
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.random.rand(0,10,25)

array([], shape=(0, 10, 25), dtype=float64)

In [6]:
np.random.rand(5,5)

array([[0.83436291, 0.66895107, 0.10758851, 0.97345335, 0.75633791],
       [0.70455087, 0.99095621, 0.5749816 , 0.90242603, 0.35531071],
       [0.9944647 , 0.67141665, 0.39655455, 0.55475564, 0.94538499],
       [0.1479987 , 0.93240285, 0.30772417, 0.35120842, 0.74922634],
       [0.17691656, 0.58616568, 0.84356395, 0.20336279, 0.01552992]])

In [7]:
arr_2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15,],[16,17,18,19,20][21,22,23,24,25]])
arr_2

TypeError: list indices must be integers or slices, not tuple

In [8]:
arr_2 = np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15,],[16,17,18,19,20][21,22,23,24,25])
arr_2

SyntaxError: invalid syntax (<ipython-input-8-75e864c383ea>, line 2)

In [9]:
arr_2d = np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15,],[16,17,18,19,20][21,22,23,24,25])
arr_2d

SyntaxError: invalid syntax (<ipython-input-9-7bd1bf954bdc>, line 2)

In [10]:
arr_2 = np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15,],[16,17,18,19,20][21,22,23,24,25]))
arr_2

TypeError: list indices must be integers or slices, not tuple