In [2]:
import numpy as np

In [6]:
arr = np.arange(25)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [8]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
arr.max()

24

In [10]:
arr.min()

0

In [11]:
arr.argmax()

24

In [12]:
arr.argmin()

0

In [13]:
nilai = np.arange(1,26)
nilai

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [15]:
nilai[10:20]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])